# Generated by Django 3.2 on 2025-01-30 10:49

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20250130_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[reviews.validators.validate_year_not_future], verbose_name='Год выпуска'),
        ),
    ]
